apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: usrs
  name: hello2-0
  annotations:
    repo: "https://git.your-big-company.com.br/lms/new-proj"
    imageregistry: "https://hub.docker.com"
    maintainer: "Navneet Lal Gupta"
    email: "navneet@example.com"
  labels:
    product: intracity
    version: stable
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 1
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo sleeping for 10 minutes; sleep 10; npm i
          restartPolicy: Never